### PR TITLE
Show organizer names for past events on chapter show page

### LINKED ISSUE #432: Add organizer names for past events on chapter show page
Currently there is no way to see who the organizers for a specific event are without clicking into the event. When we are planning a workshop it would be really helpful to see a list of  who has organized workshops in the past and that way we can see who to potentially contact. This would also give us an idea of how many workshops a single person has organized so as not to overwhelm a single volunteer.

I was thinking potentially adding a column to this [table](https://www.bridgetroll.org/chapters/3) that lists the organizers for the event would be one way to do this.

### PR DESCRIPTION
**Pull request by JayaDarby**
Hi there,
I'm new to open source commits and am happy to help out Bridge Troll. Let me know if there is anything I should've done differently. Thank you!

Fixes #432

### CODE REVIEW

**Comment by tjgrathwell** [comment]
Hey @JayaDarby, I think the intention of #432 was for this information to show up just on Chapter pages, but as written it also shows up on the Past Events index on the frontpage, making it very tall.

screen shot 2016-01-17 at 9 43 57 pm

Could you find a way to limit the places this extra column is shown?

**Comment by JayaDarby** [comment]
Okay I will fix it.

**Comment by JayaDarby** [comment]
Hi there, I see that that this table is not only rendered on the chapter show page and the home page (events index), but also rendered on the regions show page as well as the locations show page. The regions show page already has the organizers listed elsewhere, but I was wondering if you would like me to add the column to the locations show page as well? Thanks!

**Comment by tjgrathwell** [comment]
Seems good enough as-is, I've committed and deployed it plus an amendment in b542be01dc9b584c468d4e1baaa6672469731e93 to reduce the number of queries.

Thanks!

**Comment by JayaDarby** [comment]
Awesome. I did write two tests just in case- one to verify organizers aren't on the home page and one to verify that they are on the chapter show page. Was that a little overkill or would you like similar tests to be written down the road? Thanks for the feedback!

**Pull request merged**
