### PR TITLE
Adds TDD with React Course

### PR DESCRIPTION
**Pull request by kwokster10**
- PR to address issue https://github.com/railsbridge/bridge_troll/issues/564.

### TODO:
- Create TDD chapter in NYC

### CODE REVIEW

**Comment by kwokster10** [comment]
@rachelmyers

**Comment by kwokster10** [comment]
@rachelmyers It looks the build is failing from an invalid key. Is there anything I can do to fix this?

**Comment by tjgrathwell** [comment]
@kwokster10 I think your build actually failed because `bridge_troll` was using the gem `shoulda_matchers` from a git source which has since been deleted.
I've fixed the master branch to pull `shoulda_matchers` from rubygems, so it should work better if you rebase the branch and push it again.

**Comment by kwokster10** [comment]
@tjgrathwell ok, thanks for looking into it. I will rebase later today.

**Comment by kwokster10** [comment]
@tjgrathwell It looks like a Mongo key is expired: `GPG error: http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2 Release: The following signatures were invalid: KEYEXPIRED 1507497109`

**Comment by tjgrathwell** [comment]
I think the Mongo thing was just some kind of flake, because it passed on retry!

**Comment by kwokster10** [comment]
@tjgrathwell Awesome! Thanks for getting that merged. Would you also know how to create a NYC TDD chapter?

**Pull request merged**
