### PR TITLE
Style emails to look like they came from BridgeTroll

### PR DESCRIPTION
**Pull request by nfiniteset**
Hey team,

I've upgraded the email situation on BridgeTroll. Emails now have:

- A shared layout that provide a header and footer
- A shared stylesheet: mailers.css
- State-of-the-art table-based layout for mail client compatibility
- Styles inlined automatically by the premailer gem
- Previews using the Rails 4.1 preview stuff. See them here: http://localhost:3000/rails/mailers/

Emails look something like this now:
bridgetroll-email

### CODE REVIEW

**Comment by tjgrathwell** [comment]
AMAZING

... I assume, anyway. I'm scared of anything related to email styling, that it might look crazy in some email client or another. By my eye there aren't **nearly** enough tables in that layout to make the result look great in Lotus Notes, but maybe that's fine.

Looks like `rails-assets-sinonjs` somehow escaped the `Gemfile.lock` in 17a699fbcb8f0bb1040c06c0a2ee4f597e8c895b which is making the Travis build mad.

Also, could you squish down the "Remove unused images" commit such that the offending images were never added?

**Comment by tjgrathwell** [comment]
also-also, now that #300 is merged maybe apply the same layout wizardry to it too here?

**Comment by nfiniteset** [comment]
I don't know what that sinon drama was about. Why was it removed to begin with? No idea.
And `bundle install` didn't add it back to Gemfile.lock. 

Adding the rails-assets source at the top instead of just around the sinon gem got it added back into Gemfile.lock. Meh? You ok with this?


And Re: ensuring it works in many clients—I've only tested these emails in Chrome, going from my memory of quirky emails I've worked on in the past. I'll test them in some real clients once we get it hooked up to a real email server. Can I do it from the acceptance server?


Also, squashed that pesky images commit.

**Comment by tjgrathwell** [comment]
The `source do` syntax was added in Bundler 1.7 to ensure that gems from sources other than rubygems are definitely coming from from the right source, see http://bundler.io/v1.7/whats_new.html#version17

My guess is that maybe the copy of bundler that you're `bundle install`ing with is older than 1.7 and just doesn't understand that syntax? Can you try a `gem install bundler` and then bundle again with the `source do` syntax intact?

I thought about adding something to `script/bootstrap` or some other area of the app to validate that the user's Bundler is >= 1.7, but couldn't find a good way or place.

**Comment by nfiniteset** [comment]
THAT did it! Ok. I cleaned up the history there.
That was also the root of my hosed Jasmine.

**Comment by tjgrathwell** [comment]
Can you squish that last commit (6ef9d3a) onto whichever commit made `.encoded.` required? I like to have every commit passing the test suite for bisect sanity.

I'm not super-sold on the top header as it maybe over emphasizes the (questionable) "Bridge Troll" brand over the content of the email. Right now in MailCatcher it looks like this:

screen shot 2015-02-13 at 12 00 15 am

I don't know if that's representative of how it would look in a client with images disabled (how common is that, nowadays?) but the off-centering of the title is off putting.

Also the text version (does any client really care about the text version?) looks like this:

screen shot 2015-02-13 at 12 00 28 am

where the "Bridge Troll" link at the top is *definitely* out of place.

**Comment by tjgrathwell** [comment]
@nfiniteset - I've remixed the first couple of commits in this PR into f49bedae31751ff94a141dccebf6264bfb22c1af, preserving the shared layout and mail preview but none of the style changes.

While I like the updated look of the emails, I'm not sure if it's right for Bridge Troll and would like input from more voices. Please open another PR with those changes if you want to continue that conversation.

**Pull request closed without merging**
