### PR TITLE
Add new course - Intro to Android

### PR DESCRIPTION
**Pull request by kmolo**
@tjgrathwell trying to get new Intro to Android course up on BridgeTroll.org a.s.a.p. since event in the works for first and second week of August 2015:

https://github.com/mobilebridge/organizing/issues/7

### CODE REVIEW

**Comment by kmolo** [comment]
Since Travis CI build passed, and assuming PR is accepted, I don't recall what's involved in deploying (with the new course).

Curious when I might find 'Intro to Android Development' on Bridgetroll.org among the course choices dropdown menu?

**Comment by lilliealbert** [comment]
@tjgrathwell usually deploys the app after accepting PRs.

**Comment by tjgrathwell** [comment]
It's deployed! :rocket:

**Comment by kmolo** [comment]
@tjgrathwell @lilliealbert awesome!  thanks!

Also excited for the CarbonFive commitment to work with junior devs on BridgeTroll:

http://blog.carbonfive.com/2015/06/15/introducing-junior-jump-extended/

...a total win-win-win-win for all involved.

**Pull request merged**
