### PR TITLE
Pull request for issue #440 - email organizers when event is approved

### PR DESCRIPTION
**Pull request by sidhene**
Created method, mailer, and tests so that an organizer will receive an email alert when their event is approved.

### CODE REVIEW

**Comment by tjgrathwell** [comment]
Thanks @sidhene, two things:

1. Please squash the commits into a single one as described in http://railsbridge.github.io/bridge_troll/
2. Please remove the changes to `schema.rb` from the commits. The changes you have are a result of running `rake db:migrate` against a Postgres version of the database, which is different than the sqlite version we have checked in.

**Comment by sidhene** [comment]
@tjgrathwell - Something's happened with a recent update. There were a number of gems that needed installing when I pulled the latest this morning, and now a lot of tests are broken. I re-ran the setup that's described in the readme but that didn't fix it. I also tried reverting to the commit I was at before submitting the pull request (when everything was working) but that didn't fix it either. 

This looks like the kind of problem I and several others had at the last hackathon and we needed hands-on help to fix it. I don't see that happening anytime soon. 

What do you want to do?

**Comment by sidhene** [comment]
Dropping and rebuilding the database fixed this.

**Comment by sidhene** [comment]
@tjgrathwell - squash and schema changes done. Git found a 'non-fast-forward' change (probably my reversion from the fix above) and rejected it. I wanted to make sure I was submitting the squash and schema changes with all the tests working, so I've created a new pull request: https://github.com/railsbridge/bridge_troll/pull/459

**Pull request closed without merging**
