### PR TITLE
New required text field: Target audience

### PR DESCRIPTION
**Pull request by possibly**
Added a required text field that asks workshop creators to specify their "target audience." The field is not required for non-workshop events. I had to go through and change a few different tests and files to change how they created events now that there is a new required event.

Im one of the Juniors at Carbon Five working on a few stories Lillie helped us put together. The specific story I worked on is here: https://www.pivotaltracker.com/story/show/99063524

### CODE REVIEW

**Comment by tjgrathwell** [comment]
This seems pretty good, the one problem is that we've got a whole bunch of events that were created before this validation existed, which will now no longer respond true to `.valid?`. These events therefore can't be updated without skipping validation.

In the long term, we will probably go back and populate the target audience for these events, but it might be nice if the validation was configured to only run for new events. Maybe something like:

`workshop_event.validates_presence_of :target_audience, if: :target_audience_required?`

```
def target_audience_required?
  new_record? || target_audience_was
end
```

This code (hopefully) should make it so
* New events always require `target_audience` on create
* Once an event has `target_audience` set, it is required on every subsequent save

**Comment by possibly** [comment]
Thanks for the update. Working on a fix now.

**Comment by possibly** [comment]
> workshop_event.validates_presence_of :target_audience, if: :target_audience_required?

So I found that this caused non-workshop events to still require target_audience to be set. with_options seems to just append "if" checks to the end of validation statements. This means that if any of the "if" statements pass, then the validation fires.

The difference is highlighted here
```
validates_presence_of :target_audience, unless: :historical?, if: [:allow_student_rsvp?, :target_audience_required?]
```
(requires both allow_student_rsvp? and target_audience_required? to pass, great!)
vs.
```
validates_presence_of :target_audience, unless: :historical?, if: :allow_student_rsvp?, if: :target_audience_required?
```
(Either if check passing causes the validation to fire, boo) 

Anyhow. I also added the target audience to be displayed when someone opens the event (duh!).

**Comment by tjgrathwell** [comment]
It's possible your second validation variation example doesn't work because only the last of those `if:` options will be passed down into the method, ex:

```
2.2.2 :004 > {:if => :red, :if => :green, :if => :blue}
(irb):4: warning: duplicated key at line 4 ignored: :if
(irb):4: warning: duplicated key at line 4 ignored: :if
 => {:if=>:blue}
```

The array form seems to be working out, though.

The `target_audience` field doesn't actually need to show up on the event for now, so let's remove it from the `show` page. It mainly exists to require the the organizer to think about it when creating the event.

Also it should not have been put into the view as `html_safe`. The event description is inserted with `html_safe` only because we strip scary HTML tags out of the event description on the way to the database. Since there's no corresponding logic to do that for `target_audience` (and no reason for it to have HTML tags anyway) the `html_safe` is not needed.

**Comment by possibly** [comment]
Hey, I removed the `target_audience` field from the `show` page.

**Comment by tjgrathwell** [comment]
:cool:, this is now pushed and deployed :rocket:

**Pull request merged**
