### PR TITLE
Add footer with links.

### PR DESCRIPTION
**Pull request by domlet**
Taking care of this issue: [https://github.com/railsbridge/bridge_troll/issues/535](url)

### CODE REVIEW

**Comment by jhsu802701** [comment]
Here's a screenshot:
bridge_troll_footer

**Comment by ultrasaurus** [comment]
@jhsu802701  thanks for posting the screenshot!  in order to move this forward, please make a new PR  (keeping this history) then add whatever changes are needed as another commit.   Then we can look at merging your PR (with passing tests!) to get this into the app.

**Comment by jhsu802701** [comment]
I have provided an updated version of this pull request at https://github.com/railsbridge/bridge_troll/pull/608.

**Comment by jhsu802701** [comment]
I see that I need to update the tests.

**Comment by ultrasaurus** [comment]
Odd to see routing errors, from a footer change:

```
  1) arranging sections for an event groups the attendees by their chosen level
     Failure/Error: <%= link_to "Past events", controller: "events", action: "past_events" %>
     
     ActionView::Template::Error:
       No route matches {:action=>"past_events", :controller=>"events/events", :event_id=>"10"}
```

Next steps: rebase this branch on master (to pick up new version of Ruby + gems) then look at failing pages -- seems like there ought to be a way to see the images on Travis CI since they are generated as part of the tests and can be seen in the [build log](https://travis-ci.org/railsbridge/bridge_troll/builds/345830554?utm_source=github_status&utm_medium=notification).  Probably needs to be debugged locally in any case.

**Comment by michaelglass** [comment]
This was merged in #655, and is now hanging out in #676

**Pull request closed without merging**
