### PR TITLE
Update course_populator.rb

### PR DESCRIPTION
**Pull request by devraj-kumar**
bug fix undefined local variable or method `__DIR__' for CoursePopulator:Module

### CODE REVIEW

**Comment by devraj-kumar** [comment]
@michaelglass can you review this

**Comment by devraj-kumar** [comment]
issue resolved  https://github.com/railsbridge/bridge_troll/issues/909

**Comment by michaelglass** [comment]
thank you!

**Comment by devraj-kumar** [comment]
Welcome, looking forward to contributing more under your guidance

**Comment by michaelglass** [comment]
@devraj-kumar do you want guidance as to an issue to pick up off the backlog?

**Pull request merged**
