### PR TITLE
add dietary restrictions for currently checked in attendees

### PR DESCRIPTION
**Pull request by dannyshafer**
Issue #316 

Add a section on event dietary needs page (events/:id/diets) which shows the dietary of only attendees that are checked in currently as opposed to the old page which had an aggregation of all RSVPs regardless of whether or not they were attending the event.

### CODE REVIEW

**Comment by tjgrathwell** [comment]
Hey @dannyshafer, thanks for the PR. Unfortunately there's a couple of issues that prevent it from being merged.

First, I'm not sure what the intended effect of the `<span style="float: left">` elements are, but this is how the page renders on my machine:

screen shot 2016-01-24 at 10 38 44 pm

This probably happens if any of the user-entered dietary restrictions are long enough to wrap.

If you really want to lay out the sections side by side, it's probably better to use the [bootstrap grid classes](http://getbootstrap.com/css/#grid). Otherwise it seems fine to just let them stack vertically.

Second, the looping in the controller to add up the preferences is very inefficient because each `Rsvp.find` and `DietaryRestriction.find_by_rsvp_id` goes all the way back to the database.

`rack-mini-profiler` says it takes ~140 queries to render the page:

screen shot 2016-01-24 at 10 47 34 pm

by contrast, the event show page takes about 15.

Rather than adding up the diets for checked in users in a loop, you should find some way to adapt the code in [Event#dietary_restrictions_totals](https://github.com/railsbridge/bridge_troll/blob/a9f88a9e8de90f0068efa801799032a230c2b215/app/models/event.rb#L283) (which gets the restriction counts in a single query) to do the same counts for checked-in RSVPs.

**Comment by dannyshafer** [comment]
Thanks! I'll try to update it before the end of this weekend, hopefully sooner.

**Comment by dannyshafer** [comment]
I refactored it to be in the model but it still has the loop + look ups so perhaps still not there yet. Would I be thinking along the right lines that there needs to be a new scope added to Rsvp, similar to the "confirmed" one but that checks if the user is checked in?

**Comment by tjgrathwell** [comment]
Closing in favor of #466

**Pull request closed without merging**
