### PR TITLE
domlet footer (reverted ten times)

### PR DESCRIPTION
**Pull request by michaelglass**
This PR started in https://github.com/railsbridge/bridge_troll/pull/580, got merged in #655, but was reverted because it was unstyled. Then got merged again. Then got reverted again. 

This is the next round! We should be able to merge it once it's styled correctly (or maybe, once the correct CSS is included on the about page).

https://bridgetroll-staging.herokuapp.com/about

looks like
image
should look like
image

If anyone wants to hop in here and add styling, this would be ready to go!

## before merging
1. check out the about page locally to see if the footer is styled
2. deploy to staging
3. [ensure the footer is styled locally there, too](https://bridgetroll-staging.herokuapp.com/about)

### CODE REVIEW

**Comment by michaelglass** [comment]
@ultrasaurus reverted #676 because the about page was unstyled when I deployed to staging

**Comment by ultrasaurus** [comment]
Sorry not to read your comment more carefully. It would have been helpful if you also grabbed a screenshot of what it looked like when correct.  (Personally I might have left as is and opened a bug on the about page styling because the footer adds quite a bit of useful functionality and the about page isn't linked from anywhere)

I'll take another look.  It might be a good idea to have a list of links that need to be manually verified in the [Contributing Guide](https://github.com/railsbridge/bridge_troll/blob/master/CONTRIBUTING.md) -- I don't think the about page is linked from anywhere.

Thanks!

**Comment by michaelglass** [comment]
> Sorry not to read your comment more carefully. It would have been helpful if you also grabbed a screenshot of what it looked like when correct.

Yah good idea. Will drag over your screenshot to this issue.

> (Personally I might have left as is and opened a bug on the about page styling because the footer adds quite a bit of useful functionality and the about page isn't linked from anywhere)
I feel more uncomfortable making that call, but if you wanna call it, re-merge this PR!

> I'll take another look. It might be a good idea to have a list of links that need to be manually verified in the Contributing Guide.

Good idea!

> -- I don't think the about page is linked from anywhere.
I know it's linked from the logged out homepage. didn't search where else.

thank you!

**Comment by michaelglass** [comment]
@ultrasaurus I think the issue might be resolved by https://github.com/railsbridge/bridge_troll/pull/764

**Pull request merged**
