### PR TITLE
Add Todd's Go course

### PR DESCRIPTION
**Pull request by carlisia**
Add a new Go course and some minor edits to existing ones.

### CODE REVIEW

**Comment by lilliealbert** [comment]
@carlisia Did you see that the build failed? Can you fix, run the specs, and push up the fix?

**Comment by tjgrathwell** [comment]
1. The first link is defined like this: `<a href='https://bit.ly/Todd_McLeod_LHTCG'>https://twitter.com/Todd_McLeod</a>` -- why is this a bit.ly instead of a direct link?
1. The second link is also a bit.ly: `<a href='http://bit.ly/gobridge-lhtc/'>https://www.udemy.com/learn-how-to-code/</a> and at <a href='https://github.com/GoesToEleven/GolangTraining/'>https://github.com/GoesToEleven/GolangTraining/</a>` but in this case the link http://bit.ly/gobridge-lhtc/ does not work, though going directly to https://www.udemy.com/learn-how-to-code/ does.

**Comment by carlisia** [comment]
@lilliealbert I'm using bitly here to track click-through numbers.

Odd that that link is broken, I might have deleted it by mistake, but glad you caught it. I'll create another one and update this PR. Thanks.

**Comment by carlisia** [comment]
@tjgrathwell, good to merge now. Thank you!

**Comment by lilliealbert** [comment]
@carlisia Depending on the Bit.ly links working forever scares me a little bit — could there be another solution to tracking, like putting Google Analytics on the curriculum itself and looking at where the traffic is coming from? 

Putting Bit.ly links in the code feels very brittle to me.

**Comment by carlisia** [comment]
@lilliealbert I hear you. To be sure, the bitly link itself that I had added previously was never broken, I had added an extra `/` to the end of it and that was what caused it not to redirect correctly.

I don't have access to the site the bitly links are pointing to, so I can't add google analytics there.

It would be nice for us to be able to tell course donors how many hits their sites are getting from us. But if using bitly makes you uncomfortable I'll remove it.

**Comment by lilliealbert** [comment]
Interesting. If the information is ultimately going to the people who run the sites that host the curricula, it seems like they would be able to instrument those pages to know where traffic is coming from. That's a tough call.

**Comment by tjgrathwell** [comment]
Okay, it is merged and deployed as is.

Though in revisiting the issue, I think the idea of making multiple "Go Curriculum 1" and "Go Curriculum 2" courses goes a bit against the grain we've followed so far with the Rails curricula.

For Rails workshops, there is only a single Rails course, and the five levels in the Rails course description are used to determine whether attendees will use the [beginner](http://docs.railsbridge.org/intro-to-rails/), [intermediate](http://docs.railsbridge.org/job-board/), or [advanced](http://docs.railsbridge.org/message-board/) curricula.

I worry about the fragmentation that might be caused by locking a given workshop to a particular curriculum rather than just having a "Go Workshop" where attendees will be sorted into the appropriate curricula, either based on their experience or whatever the teacher prefers.

But you can probably do whatever you want as long as people learn programming!!

**Pull request merged**
