### PR TITLE
Save event filter criteria in local storage

### PR DESCRIPTION
**Pull request by nfiniteset**
EventsFitlerView handles
- filtering events on the events index page
- storing filter value in local storage
- retrieving filter value and filtering events when page loads

### CODE REVIEW

**Comment by nfiniteset** [comment]
I didn't add a spec here. The Jasmine specs seem to be totally hosed. Is that just me?

**Comment by tjgrathwell** [comment]
Both `bundle exec rake jasmine:ci` and `bundle exec rake jasmine` are working for me locally without incident; `jasmine:ci` [runs with the Travis build as well](https://travis-ci.org/railsbridge/bridge_troll/builds/50429111). Maybe YOU are the Jasmine which is hosed?

**Comment by tjgrathwell** [comment]
I think this needs to more gracefully handle the situation where a chapter was once in the dropdown but isn't on a later visit.

Right now, the `.val(chapterId)` tries to select the old chapter from the dropdown, which in my chrome is showing like this:

screen shot 2015-02-12 at 12 24 41 am

Seems like we can either
* Default it back to 'All Chapters' if the localStorage'd chapter is no longer present (easy enough)
* Add the user's previous selected chapter to the dropdown (tough because we only have the id), keep it selected, and show a proper "no events found" message in the upcoming events area. This keeps the majority of the user's context but is a lot of complexity for something that's only being persisted per-browser session.

What do you think?

**Comment by tjgrathwell** [comment]
can now be seen on the website https://bridgetroll.org

**Pull request merged**
