### PR TITLE
updated pull request for issue #440 - email organizers when event is approved

### PR DESCRIPTION
**Pull request by sidhene**
Same as pull request #458, but with change requests

### CODE REVIEW

**Comment by tjgrathwell** [comment]
Thanks @sidhene. In the future, it would be better to update the existing pull request by force-pushing to the PR's branch after rebase, instead of making a new one. Splitting out a new pull request makes the discussion harder to follow.

It also helps to [add something like "Fixes #440" to the commit message](https://help.github.com/articles/closing-issues-via-commit-messages/) to ensure that the PR is linked back to the original issue.

After a second look, I think the code in `UnpublishedEventsController` should be changed a bit. This part:
```
if @event.email_on_approval
  EventMailer.new_event(@event).deliver_now
  @event.update_attribute(:announcement_email_sent_at, DateTime.now)
else
  EventMailer.event_has_been_approved(@event).deliver_now
end
```
should probably move the `has_been_approved` mail out of the else clause like this
```
if @event.email_on_approval
  EventMailer.new_event(@event).deliver_now
  @event.update_attribute(:announcement_email_sent_at, DateTime.now)
end
EventMailer.event_has_been_approved(@event).deliver_now
```

... the `email_on_approval` flag just specifies whether region members get the announcement for the event, and doesn't really have anything to do with whether organizers should get this separate email.

This does mean that most organizers will get two emails on event approval (the organizer-focused one and the attendee-focused one), but I think that's okay.

**Comment by sidhene** [comment]
I see what you mean: send the organizer an alert their event has been approved regardless of whether they want to announce. Although this story was originally created to replace the absent signal of chapter announcement, there's no reason not to signal an organizer their event has been approved regardless.

updated and pushed

**Comment by sidhene** [comment]
hold on that. the latest merge changed some tests.

**Comment by sidhene** [comment]
Okay, it's not the merge, the merge is fine, it's this change request.

The errors are coming from another feature that I'm not familiar with, but as far as I can tell the root of the problem is that many feature tests -including this one- rely on counting email. Sending out an additional email when an event has been approved messes up their count and also the content of the email they grab for testing. I've poked at it a bit, but I don't think I'm going to be able to fix the other feature tests, and in the meanwhile I've created a situation where I have extra commits that my rebase isn't getting rid of.

What I propose is holding off on this change request, documenting the kind of breakage it can create, and proposing an additional story for an alternative to email-counting since that method seems fragile and likely to cause other breakage in the future.

Also I need to know how to fix my rebase problem.

**Comment by sidhene** [comment]
I can fix the rebase problem by creating another branch and pull request, so you can skip that part. LMK how much you care about this change request. I have the feature implemented and test coverage all nailed down otherwise.

**Comment by tjgrathwell** [comment]
Pushed an amended form of this as cc2ef5844ec747ff589a9a8d4cb51a534c6c3c0f.

**Pull request closed without merging**
