### PR TITLE
449 improve security list

### LINKED ISSUE #449: Make a new security list and change some other text
Let's remove this button: 

screen shot 2016-02-28 at 8 05 38 pm

And add a new CSV that only returns people's names, sorted alphabetically by last name, to this page:

screen shot 2016-02-28 at 8 07 07 pm

And rename the buttons and add some helper text: 

* Add a new button: Download all names for building security
  * Helper text: "Includes first and last names for all attendees"
* Download Attendee names CSV becomes **Download all attendee info**
  * Helper text: "Includes name, role, dietary info, childcare info, job details, gender, plus-one host, if they are waitlisted, and waitlist position for all RSVP'd attendees."
* Download Student Details becomes **Download basic student info**
  * Helper text: "Includes name, class level, operating system, occupation, and gender for all students"

I'm not entirely sure how the helper text should be styled — maybe instead of having a series of inline buttons, you could have the button stacked in a column with the helper text next to it. Or if it looks terrible, maybe skip the helper text for now?

### PR DESCRIPTION
**Pull request by jcdaviesauthor**
Fixes #449,  we are going to try to rename the security list route to “student_names” so that it matches the resources vs resource conventions.

No we don’t have any tests. 

We have an hour left so if its not done by then feel free to close.

### CODE REVIEW

**Comment by jcdaviesauthor** [comment]
Ok renamed and we are done.

**Comment by lilliealbert** [comment]
@jcdaviesauthor Thanks for the PR! Could you take a look at the instructions for squashing on this guide and squash all your changes into one committ? http://railsbridge.github.io/bridge_troll/ 

We try to have all the tests passing at each individual commit.

**Comment by lilliealbert** [comment]
@jcdaviesauthor Did you see my message about squashing the commits? I'd love to move forward with this commit. If you won't have time, please let me know.

**Comment by jcdaviesauthor** [comment]
So sorry yes I meant to tell you I was out of own for the last week and a half and working like crazy so I couldn't look at it. I get home tonight so I can look at it tomorrow if that is soon enough. 

So sorry I didn't message sooner. 

JC

**Comment by tjgrathwell** [comment]
Closed in favor of #463

**Pull request closed without merging**
