### PR TITLE
Add username attribute to Users

### PR DESCRIPTION
**Pull request by anymoto**
Added username attribute and display_name method to User model, in order to show the username if it exists. Otherwise, full_name is displayed. 

This display_name value is being displayed everywhere except the security download.

**Registration form:**
image

**Navigation bar:**
(User with username) 
image

(User without username)
image

**Public profile:**
(User with username)
image

(User without username)
image

**Event RSVP:**
image

**Users list:**
(Users with username) 
image

(Users without username)
image

### CODE REVIEW

**Comment by anymoto** [comment]
Broken specs :disappointed: 

I'm going to take a look tonight.

**Comment by anymoto** [comment]
Specs are green! :green_heart: :green_heart: :green_heart: :green_heart: :green_heart: :green_heart:

**Comment by lilliealbert** [comment]
Thanks for all the screenshots, @anymoto!! One thing I'd like to make a little clearer is that we still would prefer people to use their in-person names. For example, I think that it's much easier for the person doing check-ins and dividing up the classes to identify people by their names, rather than screen names. It would be a little awkward for someone calling out all the people in a section to have to list off "lilliealbert, anymoto, ilovecats324, tjgrathwell"

Maybe to solve for that a little more, we could change this text: 

> (This is the name that will be used throughout the app, including on the public event RSVP listing and most organizer views)

to 

> (This is the name that will be used for checking in to the event, the RSVP listing on the event, and organizers views like dietary restrictions and small group assignments. We recommend using whatever name you usually use in-person.)

I think it might also make sense to re-order the fields, so we ask for their Display Name first, then ask for their First/Last name after gender. What do you think?

Also, could you squash your commits down so that the specs are always passing at any given commit?

**Comment by anymoto** [comment]
@lilliealbert gotcha!

This is how it looks now: 
image

Also squashed my last commits into https://github.com/railsbridge/bridge_troll/pull/468/commits/d4b136c6f38a88929608ad33c193c4cd196113fd ...let me know if that works.

I'm just wondering now if naming this new attribute as "username" makes sense, since it's not properly a username. And display_name is used [this way](https://github.com/anymoto/bridge_troll/blob/master/app/models/user.rb#L91).

**Comment by Randall-Coding** [comment]
I'm not sure why I'm allowed to make comments here, I have nothing to do with this project.

**Pull request closed without merging**
