### PR TITLE
Add new course: Docker and Containers

### PR DESCRIPTION
**Pull request by jpetazzo**
We're going to hold a Docker workshop next week in SF for members of underrepresented communities, and we would love to announce it with BridgeTroll (even if it's on a short notice; better late than never? 

For more information, here is the [event on meetup.com](http://www.meetup.com/gobridge/events/225853880/) and the [gobridge blog post announcing the event](https://medium.com/@GolangBridge/gobridge-is-organizing-a-docker-workshop-7b8c1f5f6060).

### CODE REVIEW

**Comment by lilliealbert** [comment]
Hi Jérôme! Thanks for the pull request :smile: 

I think that adding events to Bridge Troll that are already collecting RSVPs elsewhere is generally a bad idea — students and volunteers get confused about where they need to sign up, and it tends to add more work for organizers. If the main issue is promotion, maybe we could help out in other ways — Twitter & email, perhaps?

That being said, if this is an event that you plan on running again, it seems reasonable to me to add the curriculum for the next time.

I would also love to work with the GoBridge organizers on getting them set up on Bridge Troll, so that they (you?!) don't have to use Meetup at all :palm_tree: :sunglasses: :palm_tree:

**Comment by rachelmyers** [comment]
Just to make sure I understand, you want to announce it on BridgeTroll to reach the RailsBridge people who are notified when there's a new event announced in their area, right?

In that case, @lilliealbert's comment seems right on:
>  If the main issue is promotion, maybe we could help out in other ways — Twitter & email, perhaps?

Should we merge this, but save announcing a new event for the next time around?

**Comment by jpetazzo** [comment]
Thanks a lot for the feedback!

I initially created the event on meetup.com because I naively thought that the Bridge Troll integration would magically take care of everything. Then I realized it required a bit more work and planning on my end (self-facepalming ensued :-))

A little bit of promotion would help; we have ~5 spots left (and if we hit the 25 people mark, we can bump it up to 30).

Regarding this pull request: I could close it, but keep it on the side, and if we do another event (which I sincerely hope, because I deeply care about this!) then I could re-submit the PR and use Bridge Troll for RSVPs.

Does that make sense?

Thanks again!

**Comment by lilliealbert** [comment]
Cool — I will tweet a link to the Meetup tonight!

And yeah, I think closing this and then re-opening when you've got a date for your next one sounds like a perfect plan :smile:

**Comment by jpetazzo** [comment]
Closing here for now then :-) Thanks!

**Pull request closed without merging**
