### PR TITLE
Add WTM Berlin GoBridge Workshop

### PR DESCRIPTION
**Pull request by dlsniper**
This is part of the series of events that can be found here: http://www.meetup.com/gdgberlin/events/233884279/

I'm not sure if this is the best way to add it but I can't think of another way.
Thank you.

### CODE REVIEW

**Comment by dlsniper** [comment]
cc @pisush / @carlisia

**Comment by tjgrathwell** [comment]
Hi @dlsniper, the content you added in this PR is stuff that would normally be in the **description** for an event, not the **course**.

The `Course`model exists in Bridge Troll primarily to be re-used across multiple workshops: it holds the descriptions of the levels that students sort themselves into so they can be arranged into appropriate groups on the day of the workshop.

At a higher level, I'm not sure what's happening here. It looks like you already have a Meetup event associated with this workshop, so I don't know what would be achieved by getting the event into Bridge Troll. The format (3 month long series of workshops) diverges significantly from our typical event. Is there some place where @dlsniper @carlisia and @ultrasaurus can hash this all out?

**Comment by carlisia** [comment]
@tjgrathwell they are using meetup to RSVP because there's no way to RSVP via BT. Thus this PR.

**Comment by dlsniper** [comment]
@tjgrathwell currently we are facing limitations with the current model as the workshops we have are not like anything we've had before. Until we iron out how to make this work better, I see no other choice.

I'm working on figuring out the model for making this work for us. Any help into integrating Go workshops as part of BT would be welcomed.

Thank you.

**Comment by lilliealbert** [comment]
@dlsniper Can you make a new PR with a general description of the content that will be covered, without referencing a particular event? That's the main issue with this PR.

Carlisia and I are discussing the logistics of using Bridge Troll for an ongoing event on Slack if you'd like to join us there!

**Pull request closed without merging**
