### PR TITLE
Create security list, Rename attendee names and student details

### LINKED ISSUE #449: Make a new security list and change some other text
Let's remove this button: 

screen shot 2016-02-28 at 8 05 38 pm

And add a new CSV that only returns people's names, sorted alphabetically by last name, to this page:

screen shot 2016-02-28 at 8 07 07 pm

And rename the buttons and add some helper text: 

* Add a new button: Download all names for building security
  * Helper text: "Includes first and last names for all attendees"
* Download Attendee names CSV becomes **Download all attendee info**
  * Helper text: "Includes name, role, dietary info, childcare info, job details, gender, plus-one host, if they are waitlisted, and waitlist position for all RSVP'd attendees."
* Download Student Details becomes **Download basic student info**
  * Helper text: "Includes name, class level, operating system, occupation, and gender for all students"

I'm not entirely sure how the helper text should be styled — maybe instead of having a series of inline buttons, you could have the button stacked in a column with the helper text next to it. Or if it looks terrible, maybe skip the helper text for now?

### PR DESCRIPTION
**Pull request by zspencer**
Fixes #449
 * Removed download attendee button from organizer tools index
 * Allow event organizers to download a list of student names
 * Renamed security_list to student_names
 * Fixed Download basic student info test

Deprecates #450

### CODE REVIEW

**Comment by zspencer** [comment]
@tjgrathwell - The CI failure seems to be PhantomJS not being installed on the container; but this isn't something we've changed?

**Comment by tjgrathwell** [comment]
Yeah, the PhantomJS errors are something I've seen across a couple of repos; I think it's possible something was messed up with the phantomjs .bz2 artifact it was downloading from Bitbucket. Worked fine on retry.

This PR looks good, my one quibble is it seems like StudentNamesController and the student_names route should maybe be called AttendeeNames, because right now it includes student + voluneer + organizer names.

**Comment by zspencer** [comment]
If you're willing to wait on this lil the next OS Pairing night I'll take care of the rename then but I won't have time until then.

Alternatively, merge + open a ticket and tag me in it so I can do the refactor in a later pr.

**Comment by tjgrathwell** [comment]
@zspencer I can just make the change and squash it together if you think it's reasonable, provided you think the change makes sense. I wasn't sure if I had read the code incorrectly or somesuch.

**Comment by zspencer** [comment]
I did the rename, but have to bail momentarily. Will check back later to see if I broke CI again.

**Comment by zspencer** [comment]
@tjgrathwell OK, came back and saw the build was broken. Turns out I can't spell worth a darn. Hooray CI!

Build should pass now :)

**Comment by tjgrathwell** [comment]
Pushed a slightly amended version as 5c87b601229687f4bda26b2dc13f365276d57792 ; the controller name in the route still had the misspelled name, which unfortunately wasn't exercised through test.

It is deployed now though!!! :rocket:

**Pull request closed without merging**
