### PR TITLE
Adding org leadership to profile

### PR DESCRIPTION
**Pull request by laurosilvacom**
Before fixing #510. We decided to make this small change to become familiar with the code base.

### CODE REVIEW

**Comment by ultrasaurus** [comment]
I can see that there are org leaders on production: https://www.bridgetroll.org/organizations/3
I wish I had written a note about how to make one on the command line.  I pulled this locally and tests pass fine when rebased on master, just want to test that it actually works (still) before merging.

**Comment by ultrasaurus** [comment]
How to do this is in the tests:
```
        org = create(:organization, name: 'FooBridge')
        org.leaders << @user
```

TODO:
- [ ] push branch to staging
- [ ] add org leader from heroku console
- [ ] test that it works interactively 
- [ ] merge to master

**Comment by siruguri** [comment]
Do you need to do the UAT suggested above on staging? I did it locally and it works - see screenshot below. Is that sufficient for you to merge this?

Screen Shot 2019-04-04 at 10 17 42 PM

HTH!

**Comment by ultrasaurus** [comment]
confirmation that's not on my machine works for me -- I working on this pairing with @laurosilvacom so staging was serving as another pair of "eyes"

Thanks for checking this!

**Pull request merged**
