### PR TITLE
adds a simple api to see how many events a user has attended

### PR DESCRIPTION
**Pull request by cdale77**
Hi all, this is a pull request to add a very simple json api to find out how many events a user has attended. 

We are proposing this change because we would like to add a badge on the www.railsschool.org site if one of our users has attended a RailsBridge class (many of us teach or volunteer with RailsBridge, and many of our students are also involved).

I did not create a separate API namespace because this change is so simple. Also, note this controller is not protected by auth, but we don't think that's a significant issue in this case and it greatly simplifies things. Comments or feedback welcome, we're happy to make whatever changes are necessary for this to work. Thanks!

EDIT - 2nd commit to clean up some style issues

### CODE REVIEW

**Comment by tjgrathwell** [comment]
How would railsschool.org know which users to fetch counts for? Is there going to be an "enter your Bridge Troll user id here" field on the Rails School site?

**Comment by cdale77** [comment]
@tjgrathwell That's the idea, for now. We'll probably take a screenshot to help users. 

Oauth would be cool, but that might be more than we have time for right now

**Comment by tjgrathwell** [comment]
You may want to limit the event_count to only include RSVPs where the attendee was actually checked in; just using `user.event_attendances.length` will include waitlisted and no-show RSVPs.

You could manage that either by
* Changing the controller to go straight to RSVPs and do a `user.rsvps.where('checkins_count > 0').count` or
* Adding the `checkins_count` to the `event_attendances` hash and doing any slicing and dicing you want in the API controller (you could return separate counts for the student and volunteer RSVPs, if so inclined).

(A downside of using `checkins_count` is that it will exclude RSVPs from pre-2013 meetup events, because we didn't track checkins back then.)

Also, can you squish the two commits into one?

**Comment by cdale77** [comment]
Thanks for the info, I did not realize how that worked. I made the changes and squashed all the commits so you have this change in a single commit.

**Comment by tjgrathwell** [comment]
Alright, it's now deployed at URLs such as https://www.bridgetroll.org/users/1/events

**Comment by cdale77** [comment]
Thanks!

**Pull request merged**
