### PR TITLE
Locations are sortable by their most recent event

### PR DESCRIPTION
**Pull request by LauraKirby**
This is my first pull request on an open source project and I look forward to your feedback. 
 - Add a column to the locations_table to include the date of each location's most recent event. 
 - Using the arrows located in the table header, a user may sort all locations based on the most recent event date.

### CODE REVIEW

**Comment by LauraKirby** [comment]
Fixes #376

**Comment by LauraKirby** [comment]
Here are the two database queries for before and after adding the eager loading for location events. 
Before:  
original

After (one less call to the database):   
revised

**Comment by tjgrathwell** [comment]
Looks good! Can you squash the commits into a single one as described on http://railsbridge.github.io/bridge_troll/ ?

**Comment by LauraKirby** [comment]
@tjgrathwell thanks for the feedback, the commits have been squashed.

**Comment by tjgrathwell** [comment]
Thanks @LauraKirby, I've committed this as 7372042f2e94698d59068a418b10ee40bdac0c61

I changed the commit message to make it snappier, lines like "remove white space" and "testing travis failure" don't need to be committed to the historical record :smile: 

I also added one extra amendment in edef9702c7b76e9d08e0ef24775cbb3c04606db1 -- the date field was sorting alphabetically instead of date-ly, leading to results like this

screen shot 2015-12-31 at 7 47 43 pm

Adding a `date` class to the table row gives DataTables a hint as to how to sort the field [thanks to some global table setup javascript.](https://github.com/railsbridge/bridge_troll/blob/5285bb74bc013fc7e99d8760a3e2b8ea8a6b0b87/app/assets/javascripts/tables.js.coffee#L31)

**Pull request closed without merging**
